const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={file:null,url:null,img:null,ow:0,oh:0,w:0,h:0,mode:'count',cuts:[],history:[],future:[],mime:'image/png',selectedCut:-1,zoom:'fit'};
const E={choose:$('#choose'),fileInput:$('#fileInput'),dropzone:$('#dropzone'),empty:$('#empty'),previewViewport:$('#previewViewport'),previewWrap:$('#previewWrap'),preview:$('#preview'),cuts:$('#cuts'),addCut:$('#addCut'),replaceImage:$('#replaceImage'),exportBtn:$('#export'),width:$('#width'),height:$('#height'),filename:$('#filename'),count:$('#count'),sliceHeight:$('#sliceHeight'),countBox:$('#countBox'),heightBox:$('#heightBox'),freeBox:$('#freeBox'),sliceList:$('#sliceList'),sliceCount:$('#sliceCount'),previewInfo:$('#previewInfo'),summary:$('#summary'),sizeNote:$('#sizeNote'),lock:$('#lock'),undo:$('#undo'),redo:$('#redo'),reset:$('#reset'),quality:$('#quality'),qualityValue:$('#qualityValue'),progressArea:$('#progressArea'),progress:$('#progress'),status:$('#status'),format:$('#format'),help:$('#help'),helpDialog:$('#helpDialog'),cutEditor:$('#cutEditor'),cutEditEmpty:$('#cutEditEmpty'),cutEditFields:$('#cutEditFields'),cutY:$('#cutY'),deleteSelected:$('#deleteSelected')};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function snapshot(){state.history.push({cuts:[...state.cuts],selectedCut:state.selectedCut});if(state.history.length>80)state.history.shift();state.future=[];syncUndo()}
function syncUndo(){E.undo.disabled=!state.history.length;E.redo.disabled=!state.future.length}
async function load(file){if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type))return toast('请选择 JPG、PNG 或 WebP 图片');const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{if(state.url)URL.revokeObjectURL(state.url);Object.assign(state,{file,url,img,ow:img.naturalWidth,oh:img.naturalHeight,w:img.naturalWidth,h:img.naturalHeight,mime:file.type,cuts:[],history:[],future:[],selectedCut:-1});if(state.h>50000){const r=50000/state.h;state.w=Math.round(state.w*r);state.h=50000;toast('图片已按 50000 px 工作高度等比缩放')}E.empty.hidden=true;E.previewViewport.hidden=false;E.preview.src=url;E.addCut.disabled=false;E.exportBtn.disabled=false;E.width.value=state.w;E.height.value=state.h;E.filename.value=file.name.replace(/\.[^.]+$/,'')||'长图切片';recalc();applyZoom();render();syncUndo()};img.onerror=()=>toast('图片读取失败');img.src=url}
function recalc(){if(!state.img)return;state.selectedCut=-1;if(state.mode==='count'){const n=Math.max(2,Math.min(100,+E.count.value||2));state.cuts=Array.from({length:n-1},(_,i)=>Math.round(state.h*(i+1)/n))}else if(state.mode==='height'){const sh=Math.max(100,+E.sliceHeight.value||2000);state.cuts=[];for(let y=sh;y<state.h;y+=sh)state.cuts.push(y)}else state.cuts=state.cuts.filter(y=>y>0&&y<state.h).sort((a,b)=>a-b)}
function render(){if(!state.img)return;E.cuts.innerHTML='';state.cuts.forEach((y,i)=>{const d=document.createElement('div');d.className='cut'+(i===state.selectedCut?' selected':'');d.style.top=(y/state.h*100)+'%';const lab=document.createElement('span');lab.className='cut-label';lab.textContent=`${y} px`;const del=document.createElement('button');del.className='cut-delete';del.type='button';del.textContent='×';del.onclick=e=>{e.stopPropagation();if(state.mode!=='free')switchToFree(true);snapshot();state.cuts.splice(i,1);state.selectedCut=-1;render()};d.append(del,lab);d.onclick=e=>{e.stopPropagation();if(state.mode!=='free')switchToFree(true);state.selectedCut=i;render()};if(state.mode==='free')enableDrag(d,i);E.cuts.appendChild(d)});const ys=[0,...state.cuts,state.h];E.sliceList.innerHTML='';for(let i=0;i<ys.length-1;i++){const d=document.createElement('button');d.className='slice';d.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span>${state.w} × ${ys[i+1]-ys[i]} px</span>`;d.onclick=()=>scrollToY(ys[i]);E.sliceList.appendChild(d)}E.sliceCount.textContent=ys.length-1;E.previewInfo.textContent=`${state.w} × ${state.h} px · ${(state.w*state.h/1e6).toFixed(1)} MP`;E.summary.innerHTML=`${ys.length-1} 张切片 · ${state.w} × ${state.h} px<span>所有处理均在本机完成</span>`;E.sizeNote.textContent=`原始 ${state.ow} × ${state.oh} px · 当前 ${(state.w*state.h/1e6).toFixed(1)} MP`;renderCutEditor()}
function renderCutEditor(){E.cutEditor.hidden=state.mode!=='free';const ok=state.mode==='free'&&state.selectedCut>=0&&state.selectedCut<state.cuts.length;E.cutEditEmpty.hidden=ok;E.cutEditFields.hidden=!ok;E.deleteSelected.disabled=!ok;if(ok){E.cutY.max=state.h-1;E.cutY.value=state.cuts[state.selectedCut]}}
function switchToFree(preserve=true){state.mode='free';$$('#modes button').forEach(x=>x.classList.toggle('selected',x.dataset.mode==='free'));E.countBox.hidden=true;E.heightBox.hidden=true;E.freeBox.hidden=false;if(!preserve)state.cuts=[];render()}
function enableDrag(el,i){el.onpointerdown=e=>{if(e.target.classList.contains('cut-delete'))return;e.preventDefault();e.stopPropagation();state.selectedCut=i;snapshot();el.setPointerCapture(e.pointerId);const move=ev=>{const r=E.preview.getBoundingClientRect();let y=Math.round((ev.clientY-r.top)/r.height*state.h);y=Math.max(1,Math.min(state.h-1,y));state.cuts[i]=y;const v=y;state.cuts.sort((a,b)=>a-b);state.selectedCut=state.cuts.indexOf(v);render()};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)}}
function scrollToY(y){const ratio=y/state.h;const h=E.previewWrap.getBoundingClientRect().height;E.previewViewport.scrollTo({top:Math.max(0,ratio*h-80),behavior:'smooth'})}
function applyZoom(){if(!state.img)return;const vp=Math.max(320,E.previewViewport.clientWidth-56);E.previewWrap.style.width=state.zoom==='fit'?Math.min(vp,state.w)+'px':Math.max(240,state.w*(+state.zoom))+'px'}
E.choose.onclick=()=>E.fileInput.click();E.replaceImage.onclick=()=>E.fileInput.click();E.fileInput.onchange=e=>load(e.target.files?.[0]);E.dropzone.ondragover=e=>{e.preventDefault();E.dropzone.classList.add('dragover')};E.dropzone.ondragleave=()=>E.dropzone.classList.remove('dragover');E.dropzone.ondrop=e=>{e.preventDefault();E.dropzone.classList.remove('dragover');load(e.dataTransfer.files?.[0])};document.addEventListener('paste',e=>{const f=[...e.clipboardData.items].find(x=>x.type.startsWith('image/'))?.getAsFile();if(f)load(f)});
$$('.zoom').forEach(b=>b.onclick=()=>{$$('.zoom').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.zoom=b.dataset.zoom;applyZoom()});window.onresize=()=>state.zoom==='fit'&&applyZoom();
$$('#modes button').forEach(b=>b.onclick=()=>{$$('#modes button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode;E.countBox.hidden=state.mode!=='count';E.heightBox.hidden=state.mode!=='height';E.freeBox.hidden=state.mode!=='free';recalc();render()});E.count.oninput=()=>{recalc();render()};E.sliceHeight.oninput=()=>{recalc();render()};
function resizeFrom(which){if(!state.img)return;let nw=+E.width.value,nh=+E.height.value;if(E.lock.checked){if(which==='w')nh=Math.round(nw*state.oh/state.ow);else nw=Math.round(nh*state.ow/state.oh)}if(nh>50000){nh=50000;nw=Math.round(nh*state.ow/state.oh);toast('最大工作高度为 50000 px')}const r=nh/state.h;state.cuts=state.cuts.map(y=>Math.round(y*r));state.w=Math.max(1,nw);state.h=Math.max(1,nh);E.width.value=state.w;E.height.value=state.h;if(state.mode!=='free')recalc();applyZoom();render()}E.width.onchange=()=>resizeFrom('w');E.height.onchange=()=>resizeFrom('h');$$('#scales button').forEach(b=>b.onclick=()=>{if(!state.img)return;$$('#scales button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const s=+b.dataset.scale;E.width.value=Math.round(state.ow*s);E.height.value=Math.round(state.oh*s);resizeFrom('h')});
E.addCut.onclick=()=>{if(!state.img)return;if(state.mode!=='free')switchToFree(true);snapshot();let y=Math.round(state.h/2);const r=E.preview.getBoundingClientRect(),v=E.previewViewport.getBoundingClientRect(),cy=(v.top+v.bottom)/2;if(cy>r.top&&cy<r.bottom)y=Math.round((cy-r.top)/r.height*state.h);while(state.cuts.includes(y)&&y<state.h-1)y++;state.cuts.push(y);state.cuts.sort((a,b)=>a-b);state.selectedCut=state.cuts.indexOf(y);render()};E.previewWrap.onclick=e=>{if(state.mode!=='free'||e.target.closest('.cut'))return;snapshot();const r=E.preview.getBoundingClientRect(),y=Math.max(1,Math.min(state.h-1,Math.round((e.clientY-r.top)/r.height*state.h)));state.cuts.push(y);state.cuts.sort((a,b)=>a-b);state.selectedCut=state.cuts.indexOf(y);render()};
function setY(v){if(state.selectedCut<0)return;let y=Math.max(1,Math.min(state.h-1,Math.round(v)));snapshot();state.cuts[state.selectedCut]=y;state.cuts.sort((a,b)=>a-b);state.selectedCut=state.cuts.indexOf(y);render();scrollToY(y)}E.cutY.onchange=()=>setY(+E.cutY.value);$$('.nudge button').forEach(b=>b.onclick=()=>setY(state.cuts[state.selectedCut]+(+b.dataset.delta)));E.deleteSelected.onclick=()=>{if(state.selectedCut<0)return;snapshot();state.cuts.splice(state.selectedCut,1);state.selectedCut=-1;render()};
document.addEventListener('keydown',e=>{if(state.mode!=='free'||state.selectedCut<0)return;if(e.key==='Delete'||e.key==='Backspace'){if(document.activeElement.tagName==='INPUT')return;e.preventDefault();E.deleteSelected.click()}if(e.key==='ArrowUp'||e.key==='ArrowDown'){if(document.activeElement!==E.cutY&&document.activeElement.tagName==='INPUT')return;e.preventDefault();setY(state.cuts[state.selectedCut]+(e.key==='ArrowUp'?-(e.shiftKey?10:1):(e.shiftKey?10:1)))}});
E.undo.onclick=()=>{if(!state.history.length)return;state.future.push({cuts:[...state.cuts],selectedCut:state.selectedCut});const s=state.history.pop();state.cuts=s.cuts;state.selectedCut=s.selectedCut;render();syncUndo()};E.redo.onclick=()=>{if(!state.future.length)return;state.history.push({cuts:[...state.cuts],selectedCut:state.selectedCut});const s=state.future.pop();state.cuts=s.cuts;state.selectedCut=s.selectedCut;render();syncUndo()};E.reset.onclick=()=>{if(!state.img)return;state.w=state.ow;state.h=Math.min(state.oh,50000);if(state.oh>50000)state.w=Math.round(state.ow*50000/state.oh);E.width.value=state.w;E.height.value=state.h;recalc();applyZoom();render()};E.quality.oninput=()=>E.qualityValue.textContent=E.quality.value;
function canvasBlob(c,m,q){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('编码失败')),m,q))}
E.exportBtn.onclick=async()=>{if(!state.img)return;if(typeof JSZip==='undefined')return toast('ZIP 组件加载失败，请联网后刷新');try{E.exportBtn.disabled=true;E.progressArea.hidden=false;const zip=new JSZip(),ys=[0,...state.cuts,state.h],m=E.format.value==='original'?state.mime:E.format.value,ext=m==='image/jpeg'?'jpg':m==='image/webp'?'webp':'png',q=+E.quality.value/100;for(let i=0;i<ys.length-1;i++){E.status.textContent=`正在生成 ${i+1} / ${ys.length-1}`;E.progress.value=Math.round(i/(ys.length-1)*100);const sy=ys[i]/state.h*state.oh,sh=(ys[i+1]-ys[i])/state.h*state.oh,outH=ys[i+1]-ys[i],c=document.createElement('canvas');c.width=state.w;c.height=outH;const x=c.getContext('2d',{alpha:m!=='image/jpeg'});if(m==='image/jpeg'){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)}x.drawImage(state.img,0,sy,state.ow,sh,0,0,state.w,outH);const blob=await canvasBlob(c,m,q);zip.file(`${E.filename.value||'长图切片'}_${String(i+1).padStart(2,'0')}.${ext}`,blob);c.width=c.height=1}E.status.textContent='正在打包 ZIP';const blob=await zip.generateAsync({type:'blob'},m=>E.progress.value=Math.round(m.percent));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${E.filename.value||'长图切片'}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('切片已生成')}catch(e){console.error(e);toast('导出失败，建议缩小图片后重试')}finally{E.exportBtn.disabled=false;setTimeout(()=>E.progressArea.hidden=true,1200)}};
E.help.onclick=()=>E.helpDialog.showModal();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());